version: 2
updates:
    - package-ecosystem: 'gradle' # See documentation for possible values
      registries: '*'
      directory: '/' # Location of package manifests
      schedule:
          interval: 'daily'
      ignore:
          - dependency-name: 'dev.isxander:yet-another-config-lib' # Dependabot is not aware of modloaders and minecraft versions.
          - dependency-name: 'com.terraformersmc:modmenu' # Dependabot is not aware of modloaders and minecraft versions.
