// For some reason dependabot has issues finding dependency versions in gradle.properties. This allows dependabot to get its act together
ext {
    // Fabric Properties
    // check these on https://fabricmc.net/develop
    minecraft_version = '26.2'
    loader_version = '0.19.3'
    loom_version = '1.16-SNAPSHOT'

    // Mod Properties
    mod_version = '1.9.1'
    maven_group = 'dev.creesch'
    archives_base_name = 'web-chat'

    // Dependencies
    fabric_version = '0.153.0+26.2'
    yacl_version = '3.9.5+26.2-fabric'
    mod_menu_version = '20.0.0-beta.4'

    // Generic java dependencies
    javalin_version = '7.2.3'
    lombok_version = '1.18.46'
    xerial_version = '3.53.2.0'
}
